import type { Booking, Category, Expert, Location, Notification } from "../types"

// Update the categories array to use the new icons
export const categories: Category[] = [
  { id: "1", name: "Mechanic", icon: "tool" },
  { id: "2", name: "Electrician", icon: "zap" },
  { id: "3", name: "Plumber", icon: "droplet" },
  { id: "4", name: "Carpenter", icon: "hammer" },
  { id: "5", name: "Painter", icon: "paintbrush" },
  { id: "6", name: "HVAC Technician", icon: "thermometer" },
  { id: "7", name: "Landscaper", icon: "scissors" },
  { id: "8", name: "Appliance Repair", icon: "washing-machine" },
  { id: "9", name: "Locksmith", icon: "lock" },
]

export const locations: Location[] = [
  { id: "1", name: "Angeles City" },
  { id: "2", name: "Manila" },
  { id: "3", name: "Cebu City" },
  { id: "4", name: "Davao City" },
  { id: "5", name: "Quezon City" },
  { id: "6", name: "Baguio City" },
]

export const experts: Expert[] = [
  {
    id: "1",
    name: "John Doe",
    profession: "Mechanic",
    verified: true,
    price: "P300/job",
    description:
      "Experienced mechanic specializing in engine repairs and diagnostics with over 10 years of experience. Available for emergency repairs and regular maintenance.",
    rating: 4.8,
    image: null,
    location: "Angeles City",
    experience: "10 years",
    completedJobs: 124,
    contactNumber: "+63 912 345 6789",
    email: "john.doe@example.com",
  },
  {
    id: "2",
    name: "Jane Smith",
    profession: "Electrician",
    verified: true,
    price: "P350/job",
    description:
      "Licensed electrician with expertise in residential and commercial electrical systems. Specializing in wiring, installations, and troubleshooting electrical issues.",
    rating: 4.5,
    image: null,
    location: "Manila",
    experience: "7 years",
    completedJobs: 198,
    contactNumber: "+63 912 345 6790",
    email: "jane.smith@example.com",
  },
  {
    id: "3",
    name: "Robert Johnson",
    profession: "Plumber",
    verified: true,
    price: "P280/job",
    description:
      "Professional plumber offering services for pipe repairs, installations, and drainage solutions. Available 24/7 for emergency plumbing issues.",
    rating: 4.7,
    image: null,
    location: "Cebu City",
    experience: "5 years",
    completedJobs: 87,
    contactNumber: "+63 912 345 6791",
    email: "robert.johnson@example.com",
  },
  {
    id: "4",
    name: "Maria Garcia",
    profession: "Carpenter",
    verified: true,
    price: "P320/job",
    description:
      "Skilled carpenter with experience in furniture making, repairs, and custom woodworking. Attention to detail and quality craftsmanship guaranteed.",
    rating: 4.6,
    image: null,
    location: "Davao City",
    experience: "8 years",
    completedJobs: 112,
    contactNumber: "+63 912 345 6792",
    email: "maria.garcia@example.com",
  },
  {
    id: "5",
    name: "David Lee",
    profession: "Painter",
    verified: true,
    price: "P250/job",
    description:
      "Professional painter offering interior and exterior painting services. Specializing in residential and commercial projects with clean, precise work.",
    rating: 4.9,
    image: null,
    location: "Quezon City",
    experience: "6 years",
    completedJobs: 95,
    contactNumber: "+63 912 345 6793",
    email: "david.lee@example.com",
  },
  {
    id: "6",
    name: "Sarah Wilson",
    profession: "HVAC Technician",
    verified: true,
    price: "P400/job",
    description:
      "Certified HVAC technician specializing in air conditioning and heating system installation, maintenance, and repairs. Available for emergency service calls.",
    rating: 4.7,
    image: null,
    location: "Manila",
    experience: "9 years",
    completedJobs: 156,
    contactNumber: "+63 912 345 6794",
    email: "sarah.wilson@example.com",
  },
  {
    id: "7",
    name: "Michael Brown",
    profession: "Landscaper",
    verified: false,
    price: "P280/job",
    description:
      "Professional landscaper offering garden design, lawn maintenance, and outdoor space transformation. Creating beautiful outdoor environments for homes and businesses.",
    rating: 4.4,
    image: null,
    location: "Baguio City",
    experience: "4 years",
    completedJobs: 68,
    contactNumber: "+63 912 345 6795",
    email: "michael.brown@example.com",
  },
  {
    id: "8",
    name: "Jennifer Taylor",
    profession: "Appliance Repair",
    verified: true,
    price: "P350/job",
    description:
      "Experienced technician specializing in refrigerator, washing machine, dryer, and dishwasher repairs. Fast and reliable service for all major brands.",
    rating: 4.8,
    image: null,
    location: "Angeles City",
    experience: "7 years",
    completedJobs: 134,
    contactNumber: "+63 912 345 6796",
    email: "jennifer.taylor@example.com",
  },
  {
    id: "9",
    name: "Carlos Rodriguez",
    profession: "Locksmith",
    verified: true,
    price: "P300/job",
    description:
      "Professional locksmith providing emergency lockout services, lock installation, key duplication, and security system setup. Available 24/7 for urgent needs.",
    rating: 4.9,
    image: null,
    location: "Cebu City",
    experience: "11 years",
    completedJobs: 215,
    contactNumber: "+63 912 345 6797",
    email: "carlos.rodriguez@example.com",
  },
  {
    id: "10",
    name: "Lisa Chen",
    profession: "Electrician",
    verified: true,
    price: "P330/job",
    description:
      "Certified electrician with expertise in smart home installations, electrical panel upgrades, and troubleshooting. Safety and quality are my top priorities.",
    rating: 4.6,
    image: null,
    location: "Davao City",
    experience: "6 years",
    completedJobs: 103,
    contactNumber: "+63 912 345 6798",
    email: "lisa.chen@example.com",
  },
]

export const notifications: Notification[] = [
  {
    id: "1",
    title: "Booking Confirmed",
    message: "Your booking with John Doe has been confirmed for tomorrow at 10:00 AM.",
    time: "2 hours ago",
    read: false,
  },
  {
    id: "2",
    title: "New Message",
    message: "You have a new message from Jane Smith regarding your electrical issue.",
    time: "1 day ago",
    read: true,
  },
  {
    id: "3",
    title: "Service Completed",
    message: "Robert Johnson has marked your plumbing service as completed. Please leave a review.",
    time: "3 days ago",
    read: true,
  },
  {
    id: "4",
    title: "New Message",
    message: "Maria Garcia has sent you a quote for the carpentry work you requested.",
    time: "4 days ago",
    read: false,
  },
  {
    id: "5",
    title: "Booking Reminder",
    message: "Reminder: Your appointment with David Lee is scheduled for tomorrow at 2:00 PM.",
    time: "5 days ago",
    read: true,
  },
]

export const bookings: Booking[] = [
  {
    id: "1",
    expertId: "1",
    expertName: "John Doe",
    service: "Car Repair",
    date: "2023-04-15",
    time: "10:00 AM",
    status: "upcoming",
  },
  {
    id: "2",
    expertId: "2",
    expertName: "Jane Smith",
    service: "Electrical Wiring",
    date: "2023-04-12",
    time: "2:30 PM",
    status: "completed",
  },
  {
    id: "3",
    expertId: "5",
    expertName: "David Lee",
    service: "House Painting",
    date: "2023-04-18",
    time: "9:00 AM",
    status: "upcoming",
  },
]

